name: tests

on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Change file permissions
      run: chmod +r .github/workflows/tests.yml

    - name: Build and run tests
      run: make test CFLAGS=-fPIC
