name: tests
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1

    - name: List files in the directory
      run: ls

    - name: Add execution permissions
      run: chmod +x test_program

    - name: make run
      run: make tests 

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: compiled-${{ matrix.os }}
        path: .
