name: tests
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Change file permissions
      run: chmod +r tests.yml

    - name: Build and run tests
      run: make test CFLAGS=-fPIC
